[package]
name = "cambio_logic"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = {version = "0.16.1", default-features = false, features = ["serialize", "bevy_log"]}
serde = { version = "1.0.219", features = ["derive"] }
strum = "0.27.2"
strum_macros = "0.27.2"
rstest = "0.26.1"


